### ISSUE TITLE
Podfile error on iOS device. 

### ISSUE THREAD

**Issue by Samaritan1011001** [loup-v/geolocation#11]
Thanks for the plugin.
I am trying to use it in my app and when I use it and run my app on an iPhone 7 iOS 11.2.5 it throws the following error while running the pod install:
``` Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.```

**Comment by Samaritan1011001** [comment]
@lukaspili Can this be addressed soon? It would really help if we could solve it soon. It's critical for the app I am building.

**Comment by MiguelCatalan** [comment]
Correct me if I am wrong but I think the minimum target to use this plugin is `9.0`

**Comment by anilcancakir** [comment]
I changed my ios version in Podfile but i continue giving errors. Let's see my screenshot.
![image](https://user-images.githubusercontent.com/21953173/39606509-816de8e2-4f3e-11e8-994f-0d60df3185c4.png)

**Comment by stevetkdo** [comment]
I ran up against the same problem as you are seeing. I'm fairly new to Flutter but have developed native iOS apps for quite some time, so was able to unpick the problems here.

Firstly, as you have noted, you need to add `platform :ios, '9.0'` to your `Podfile`. You will need to add `use_frameworks!` to the target section for `Runner`, it should look like this:

```
target 'Runner' do
  use_frameworks!
```

Once this has been setup, you will need to satisfy XCode regarding the version of swift thats being used. For reference, I am using XCode 9.3:

<img width="642" alt="screen shot 2018-05-08 at 06 40 45" src="https://user-images.githubusercontent.com/3032418/39739824-d2e20998-528a-11e8-8df8-a5559a23d08d.png">

To do this, open up the project workspace, this will be in the iOS folder and is named `Runner.xcworkspace`. **Do not** open `Runner.xcodeproj`. Once open, It will look something like this:

<img width="1512" alt="screen shot 2018-05-08 at 06 43 40" src="https://user-images.githubusercontent.com/3032418/39740047-c80a471e-528b-11e8-9122-de770f10ed47.png">

Follow these steps:

1) Click on `Pods`.
2) In `targets`, click on `geolocation`.
3) Click on `Build Settings`.
4) Ensure you have `All` and `combined` highlighted in Blue.
5) Enter `swift` in the search bar to filter all the unwanted stuff.
6) Locate `Swift Language Version` in the `Swift Compiler - Language` section and set it to `4.1`.

Once all these steps are completed, you will now be getting a totally different error:

`'geolocation/GeolocationPlugin.h' file not found`

To fix this, we need to goto the `Build Phases` tab:

<img width="1512" alt="screen shot 2018-05-08 at 08 32 17" src="https://user-images.githubusercontent.com/3032418/39744003-adedcc52-529a-11e8-9b98-29d3e0f9bd0f.png">

1) Click on `Build Phases`.
2) Expand the `Headers` section.

The `GeolocationPlugin.h` should be in the public group list, not the project group. To change this, right click and select `Mode to public group`:

<img width="584" alt="screen shot 2018-05-08 at 08 33 56" src="https://user-images.githubusercontent.com/3032418/39744471-4a32b7ac-529c-11e8-9d22-05005eaba697.png">

You should now be able to build (In XCode, press CMD + B).

**Comment by Blaxou** [comment]
Hey ! Had the same problem and did what you advised, but I find myself with another error in the end : 
<img width="1512" alt="capture d ecran 2018-05-18 a 19 01 12" src="https://user-images.githubusercontent.com/25441359/40247799-e043680c-5acd-11e8-95a4-8b13fd979fc8.png">
Any idea as how to fix it ?

**Comment by alfanhui** [comment]
@Blaxou After following @stevetkdo's great pointers, I still had the same problem as you. I managed to resolve it further by opening terminal > `pod update` in ios folder. Hope this helps!

**Comment by lukaspili** [comment]
Closing because stale. Please open a new issue if it's still causing problems.
