### ISSUE TITLE
Doesn't work with Android project using com.google.gms:google-services:3.2.1

### ISSUE THREAD

**Issue by vagrantrobbie** [loup-v/geolocation#2]
I am using the Firebase services but these all seem to use v11.8.0 and I keep getting a "merge dex" Exception. I know I am a bad person for hardcoding your implementation to use 
implementation "com.google.android.gms:play-services-location:_11.8.0_"

Is there a better way to do handle this situation?

**Comment by lukaspili** [comment]
Thanks for the report, I will check today what's the best way to solve it.

**Comment by vagrantrobbie** [comment]
This is a much safer fix for now.

I have removed my hardcoded version from your plugin and added to my android/app/build.gradle, just before dependencies:

configurations.all {
    resolutionStrategy {
        force 'com.google.android.gms:play-services-location:11.8.0'
    }
}

dependencies {
 ...

**Comment by lukaspili** [comment]
Indeed, I would even suggest:

```groovy
configurations.all {
    resolutionStrategy {
        eachDependency { details ->
            if (details.requested.group == 'com.google.android.gms' ||
                    details.requested.group == 'com.google.firebase') {
                details.useVersion "your version"
            }
        }
    }
}
```
