### ISSUE TITLE
Crash, java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api

### ISSUE THREAD

**Issue by manuelgomes2** [loup-v/geolocation#21]
As soon as i add the geolocation to my pubspec the app starts to crash whenever i try to use this plugin - java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api
I am using:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.4.5-pre.69, on Microsoft Windows [Version 10.0.16299.371], locale pt-PT)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 32-bit edition (version 1.23.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by rlee1990** [comment]
Have the same issue.

**Comment by lukaspili** [comment]
Sorry for the delay. It's fixed in the latest release 1.0.0.
