### ISSUE TITLE
Please create new version of "currentLocation" function as a Promise

### ISSUE THREAD

**Issue by lunvjp** [loup-v/geolocation#23]
For some reasons, can we make it like a Promise so we can use it with Synchronous coding with await/sync?
Now, this function returns a Stream, right? I hope I can get the value of currentLocation in initState function by using with "await".
Thanks for your time. Let me know if it's not clear for you. Thanks!

**Comment by lunvjp** [comment]
Or maybe we can create it with StreamController? Thanks

**Comment by lukaspili** [comment]
You can already do that using:

```dart
LocationResult result = await Geolocation.currentLocation().single;
```
