### ISSUE TITLE
Raise com.google.android.gms version

### ISSUE THREAD

**Issue by ghost** [loup-v/geolocation#27]
I had to force a higher version for com.google.android.gms. I am currently using 15.0.1, which appears to work. This version is requested by the [google maps plugin](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter) by google.

To work around this I added the following the build.grade:
```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.android.gms') {
                details.useVersion "15.0.1"
            }
        }
    }
}
```
This works, but a proper fix would be to raise the upper version bound.

**Comment by lukaspili** [comment]
Sorry for the delay. It's fixed in the latest release 1.0.0.
