### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by manuelgomes2** [loup-v/geolocation#29]
running flutter build ios --release :

    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/****/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-0.0.1/ios/Classes/GeolocatorPlugin.m:2:9: fatal error: 'geolocator/geolocator-Swift.h' file not found
    #import <geolocator/geolocator-Swift.h>

My doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.3 17D102, locale pt-PT)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✗] Android Studio (not installed)
[!] VS Code (version 1.14.2)
[!] Connected devices
    ! No devices available

**Comment by lukaspili** [comment]
This error is about another plugin named `geolocator`.
The plugin here is `geolocation`.

**Comment by lukaspili** [comment]
Let me know if you find anything related to geolocation plugin.
I will close in the meantime.
