### ISSUE TITLE
Building for release with minifyEnabled true not working

### ISSUE THREAD

**Issue by dducret** [loup-v/geolocation#38]
When I build for release with option minifyEnabled true in build-grable, 
the plugin crash when I call Geolocation.requestLocationPermission with error:
FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(60)] Check failed: CheckException(env).

for information pubsec.yaml:
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.1
  intl: ^0.15.0
  intl_translation: ^0.16.7
  url_launcher: ^3.0.0
  font_awesome_flutter: ^7.0.0
  geolocation: ^0.2.1

**Comment by lukaspili** [comment]
Sorry for the delay. It should be fixed in the latest release 1.0.0.
