### ISSUE TITLE
stream_channels plugin dependency error: MissingPluginException implementation for method listen#x

### ISSUE THREAD

**Issue by jaco-pixeldump** [loup-v/geolocation#43]
hello,

there is severe issue when invoking stream.listen (e.g. in tab_location.dart @~52), it causes such exception, maybe due to an erratic management of id in stream_channel.

regards
Jaco

**Comment by jiachen247** [comment]
same issue.

**Comment by lukaspili** [comment]
Sorry for the delay. It should be fixed in the latest release 1.0.0.
