### ISSUE TITLE
 The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported

### ISSUE THREAD

**Issue by delphiy** [loup-v/geolocation#46]
Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

**Comment by lukaspili** [comment]
Sorry for the delay. It should be fixed in the latest release 1.0.0.
