### ISSUE TITLE
fatal error: 'geolocation/geolocation-Swift.h' file not found

### ISSUE THREAD

**Issue by delphiy** [loup-v/geolocation#47]
Xcode's output:
↳
    /Users/delphix/Documents/Sdk/flutter/.pub-cache/git/geolocation-5f7e2ec8a00fa0c020791c5b0c1844b2bd320c05/ios/Classes/GeolocationPlugin.m:7:9: fatal error: 'geolocation/geolocation-Swift.h' file not found
    #import <geolocation/geolocation-Swift.h>

**Comment by lukaspili** [comment]
Sorry for the delay. It should be fixed in the latest release 1.0.0.
