### ISSUE TITLE
How to enable background record of location?

### ISSUE THREAD

**Issue by eliashdezr** [loup-v/geolocation#5]
If the user closes the application or if it shuts off the screen, it is possible to keep recording the user location?

**Comment by lukaspili** [comment]
Continuous location updates will be released tomorrow. However it won't ship with support for background location updates. I'm not sure how to handle this scenarios with Flutter plugin yet, as the logic is very different on iOS vs Android, and the OS will restart the app with a special argument containing the location.

Note: Background location updates is a confusing term, as it means the application was killed by the OS while being _in background_ and while listening for location updates. For apps that are still active but just offscreen (_in background_), you will be able to continue to record the location.

**Comment by lukaspili** [comment]
Released in 0.2.1.
Let me know if that works for you and feel free to reopen otherwise.
