### ISSUE TITLE
Republished package [new_geolocation]

### ISSUE THREAD

**Issue by alfanhui** [loup-v/geolocation#50]
I have republished this packaged aptly named: [new_geolocation](https://pub.dev/packages/new_geolocation)

I have included most of the items in PR as of today.

Feel free to submit new PRs into my [fork ](https://github.com/alfanhui/geolocation)for review.

**Comment by lukaspili** [comment]
Hello @alfanhui, I'm restarting maintenance of the package.
Would you be interested to merge your fork and collaborate on this package instead?
In January I'm planning to make a big overhaul of the code base, provide web integration and start working on missing features.

**Comment by alfanhui** [comment]
Hey @lukaspili, ill get a PR sorted for you. Thank you for your original contribution.

**Comment by lukaspili** [comment]
Great thanks! I'll wait on your PR and will use as it as a starting point to plan the next work.

**Comment by alfanhui** [comment]
Ok, thats the PR ready for review. Sorry it taken me so long to do.
