### ISSUE TITLE
Android - currentLocation won't update location

### ISSUE THREAD

**Issue by urbandove** [loup-v/geolocation#8]
calling currentLocation on the android emulator will return the last known location - and if a location is not available (eg if you turned off location and then turned it back on), it will return nothing.
It probably should in should try to get the location rather than failing without trying.

Also - in order to test out different locations I have to go to the maps app after changing the emulator location before currentLocation will pick up on the new location,.

I tried to use singleLocationUpdate on android but had the same issues. In light of the above, what is your advice If I want a single updated location.

**Comment by argamanza** [comment]
+1

Any news about this issue?

**Comment by SoaresGabriel** [comment]
I'm having the same issue.

**Comment by Asoseil** [comment]
same problem, how to solve?

**Comment by ankushvangari** [comment]
Same problem. Only workaround I could find was to use continuous location and cancel once it got a result.

**Comment by lukaspili** [comment]
Sorry for the delay. It's fixed in the latest release 1.0.0.
